### ISSUE TITLE
Folder structure titles are repetitive

### ISSUE THREAD

**Issue by thawn** [BiAPoL/Image-data-science-with-Python-and-Napari-EPFL2022#2]
suggest to rename the subsection titles to something else than "Folder structure" (if we decide to keep that section)

**Comment by haesleinhuepf** [comment]
I presume you refer to these two pages 

* https://biapol.github.io/Image-data-science-with-Python-and-Napari-EPFL2022/day1x_Folder_Structures/05_Folder_structures.html
* https://biapol.github.io/Image-data-science-with-Python-and-Napari-EPFL2022/day1x_Folder_Structures/06_Folder_structures2.html

I like the content (very well prepared by Marcelo). However, we may not have the time during this course. If you remove it this time, that'll be ok with me.

**Comment by haesleinhuepf** [comment]
We could use the slides in the good scientific practice session on Friday...

**Comment by thawn** [comment]
I was planning to show these two notebooks on Day1 in the afternoon after introducing conditions, loops and functions (as we currently have it in the [planning spreadsheet](https://docs.google.com/spreadsheets/d/1lotS7QcjTVB92mc4lFVe7mOQxVeStwEnIpWo1nbxTiQ/edit#gid=0)).
Or do you think that will be too tight for the 90min slot?

How about changing the title of the first notebook to "Simple Folder Structures" and the second to "Advanced Folder Structures"
